### ISSUE TITLE
ansible-runner playbook execution via python consistently returns status `failed`

### ISSUE THREAD

**Issue by devdkerr** [ansible/ansible-runner#618] opened 2021-01-22 04:51 UTC
I am using `ansible_runner` as a python module for executing a playbook from a data object, but regularly get `status` failed when the same playbook run via `ansible-playbook` succeeds without error. To debug the issue I have dumped the object to a file and attempted to run the playbook file via `ansible_runner` with the same results (`status` is failed).

The example code is as follows:

```python
import ansible_runner
result = ansible_runner.run(
    playbook=[{
        'hosts': '<inventory name>',
        'gather_facts': False,
        'tasks': [{'action': {'module': 'ping'}}],
    }],
)
print (result.status)
```

This results in the output `failed`, consistently for over twenty different inventory hosts including `localhost`. The same playbook run via `ansible-playbook` results in successful execution and stdout results.

**Comment by Akasurde** [comment] 2022-04-28 15:05
@devdkerr Thanks for reporting this issue. I am not able to reproduce this issue. 

```
# python main.py
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'

PLAY [localhost] ***************************************************************

TASK [ping] ********************************************************************
ok: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
successful
```

Can you please provide additional information to reproduce this issue? Thanks in advance.

**Comment by bpedersen2** [comment] 2022-04-29 07:08
Looks like you need to pass a (python) list of hosts as host param, not an inventory name or you should pass the inventory param to run, not  as part of the playbook.

**Comment by Akasurde** [comment] 2022-08-09 12:17
I will go ahead and close this issue as the required information is missing. Please feel free to re-open this issue. Thanks.

**Closed as completed** 2022-08-09 12:17 UTC
