### ISSUE TITLE
ansible-runner 2.2.0 docker image

### ISSUE THREAD

**Issue by ryanmerolle** [ansible/ansible-runner#1076] opened 2022-05-17 13:18 UTC
ansible-runner 2.2.0 was released 10 days ago, but the ansible-runner image on quay has been last built/published 19 days ago.

**Comment by Shrews** [comment] 2022-05-18 14:40
Duplicate of https://github.com/ansible/ansible-runner/issues/1064

As already pointed out [here](https://github.com/ansible/ansible-runner/issues/1064#issuecomment-1118481247), [here](https://github.com/ansible/ansible-builder/issues/377#issuecomment-1122651459) and [here](https://github.com/ansible/ansible-builder/issues/376#issuecomment-1118481665), we are actively working on a new container release process and ask for your patience while we sort through the process.

**Closed as completed by Shrews** 2022-05-18 14:40 UTC

**Comment by ryanmerolle** [comment] 2022-05-18 14:51
Apparently I am loosing it.   I came back from vacation and thought I only mentioned on ansible-builder.
