### ISSUE TITLE
Unexpected Exception when using cache_plugin FQCN with a dynamic inventory

### ISSUE THREAD

**Issue by stefangluszek** [ansible/ansible-runner#1032] opened 2022-04-07 16:34 UTC
Steps to reproduce:
test.py:
```
import ansible_runner

r = ansible_runner.run(
    host_pattern='all',
    module='ping',
    inventory='/tmp/aws_ec2.yml'
```

aws_ec2.yml content:
```
---
plugin: "aws_ec2"
cache: yes
cache_plugin: ansible.builtin.jsonfile
cache_timeout: 60
```

Running `python test.py` results in:
```
ERROR! Unexpected Exception, this is probably a bug: 'Requested entry (plugin_type: cache plugin: jsonfile setting: _prefix ) was not defined in configuration.'
the full traceback was:

Traceback (most recent call last):
  File "/home/stefang/workspace/ansible-runner/.venv/lib/python3.8/site-packages/ansible/plugins/__init__.py", line 58, in get_option
    option_value = C.config.get_config_value(option, plugin_type=get_plugin_class(self), plugin_name=self._load_name, variables=hostvars)
  File "/home/stefang/workspace/ansible-runner/.venv/lib/python3.8/site-packages/ansible/config/manager.py", line 425, in get_config_value
    value, _drop = self.get_config_value_and_origin(config, cfile=cfile, plugin_type=plugin_type, plugin_name=plugin_name,
  File "/home/stefang/workspace/ansible-runner/.venv/lib/python3.8/site-packages/ansible/config/manager.py", line 558, in get_config_value_and_origin
    raise AnsibleError('Requested entry (%s) was not defined in configuration.' % to_native(_get_entry(plugin_type, plugin_name, config)))
ansible.errors.AnsibleError: Requested entry (plugin_type: cache plugin: jsonfile setting: _prefix ) was not defined in configuration.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stefang/workspace/ansible-runner/.venv/bin/ansible", line 128, in <module>
    exit_code = cli.run()
  File "/home/stefang/workspace/ansible-runner/.venv/lib/python3.8/site-packages/ansible/cli/adhoc.py", line 172, in run
    result = self._tqm.run(play)
  File "/home/stefang/workspace/ansible-runner/.venv/lib/python3.8/site-packages/ansible/executor/task_queue_manager.py", line 321, in run
    play_return = strategy.run(iterator, play_context)
  File "/home/stefang/workspace/ansible-runner/.venv/lib/python3.8/site-packages/ansible/plugins/strategy/linear.py", line 330, in run
    results += self._wait_on_pending_results(iterator)
  File "/home/stefang/workspace/ansible-runner/.venv/lib/python3.8/site-packages/ansible/plugins/strategy/__init__.py", line 818, in _wait_on_pending_results
    results = self._process_pending_results(iterator)
  File "/home/stefang/workspace/ansible-runner/.venv/lib/python3.8/site-packages/ansible/plugins/strategy/__init__.py", line 136, in inner
    results = func(self, iterator, one_pass=one_pass, max_passes=max_passes, do_handlers=do_handlers)
  File "/home/stefang/workspace/ansible-runner/.venv/lib/python3.8/site-packages/ansible/plugins/strategy/__init__.py", line 707, in _process_pending_results
    self._variable_manager.set_host_facts(target_host, result_item['ansible_facts'].copy())
  File "/home/stefang/workspace/ansible-runner/.venv/lib/python3.8/site-packages/ansible/vars/manager.py", line 682, in set_host_facts
    self._fact_cache[host] = host_cache
  File "/home/stefang/workspace/ansible-runner/.venv/lib/python3.8/site-packages/ansible/vars/fact_cache.py", line 36, in __setitem__
    self._plugin.set(key, value)
  File "/home/stefang/workspace/ansible-runner/.venv/lib/python3.8/site-packages/ansible/plugins/cache/__init__.py", line 164, in set
    cachefile = self._get_cache_file_name(key)
  File "/home/stefang/workspace/ansible-runner/.venv/lib/python3.8/site-packages/ansible/plugins/cache/__init__.py", line 125, in _get_cache_file_name
    prefix = self.get_option('_prefix')
  File "/home/stefang/workspace/ansible-runner/.venv/lib/python3.8/site-packages/ansible/plugins/__init__.py", line 60, in get_option
    raise KeyError(to_native(e))
KeyError: 'Requested entry (plugin_type: cache plugin: jsonfile setting: _prefix ) was not defined in configuration.'
```
Changing `cache_plugin: ansible.builtin.jsonfile` to `cache_plugin: jsonfile` solves the issue. But the recommended way is to use FQCN and it running `ansible -m ping all -i aws_ec2.yml` works correctly with `cache_plugin: ansible.builtin.jsonfile`

**Comment by eqrx** [comment] 2022-04-19 13:23
Hey! Thank you for the reproducer, we will look into it :)

**Comment by Akasurde** [comment] 2022-04-19 14:10
@stefangluszek What is the version of Ansible used?

**Comment by stefangluszek** [comment] 2022-04-19 14:21
> @stefangluszek What is the version of Ansible used?

`ansible [core 2.12.4]`

**Comment by sivel** [comment] 2022-04-27 14:45
I wonder if this has something to do with the `fact_cache_type` for `BaseConfig` and runner setting env vars for `ANSIBLE_CACHE_PLUGIN` and `ANSIBLE_CACHE_PLUGIN_CONNECTION`.  At first glance it seems incompatible to want to configure those outside of runner, meaning that ansible.cfg and inventory configs should not attempt to set them when using runner, but instead set `fact_cache_type` within runner.

This may still be a bug in core fwiw, even though it seems to be caused by runner trying to control behaviors.

**Comment by bcoca** [comment] 2022-04-27 15:08
can you test the following PR?

**Comment by sivel** [comment] 2022-04-28 22:26
We got an issue report about this yesterday too at https://github.com/ansible/ansible/issues/77669

https://github.com/ansible/ansible/pull/77659 has been merged and to address this.

**Comment by Akasurde** [comment] 2022-04-29 03:27
Closing this issue as PR ansible/ansible#77659 is merged. Please feel free to re-open the issue if the problem persists.

**Closed as completed by Akasurde** 2022-04-29 03:27 UTC
Labels: verified
