### ISSUE TITLE
ssh_key write error on CIFS/SMB file system

### ISSUE THREAD

**Issue by refactranthony** [ansible/ansible-runner#302] opened 2019-05-24 20:17 UTC
When providing an SSH key (env/ssh_key), using an `artifact_dir` that points to a CIFS file system, we are encountering this error:

```
OSError: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible_runner/interface.py", line 174, in run_async
    r = init_runner(**kwargs)
  File "/usr/lib/python2.7/site-packages/ansible_runner/interface.py", line 65, in init_runner
    rc.prepare()
  File "/usr/lib/python2.7/site-packages/ansible_runner/runner_config.py", line 168, in prepare
    open_fifo_write(self.ssh_key_path, self.ssh_key_data)
  File "/usr/lib/python2.7/site-packages/ansible_runner/utils.py", line 342, in open_fifo_write
    os.mkfifo(path, stat.S_IRUSR | stat.S_IWUSR)
```

I don't believe CIFS supports FIFO/mkfifo. This is a problem when using a network mounted volume for the artifacts directory (which seems like it would be a common use case, particularly when running in a Docker container). 

See here: 
https://github.com/ansible/ansible-runner/blob/master/ansible_runner/runner_config.py#L166
https://github.com/ansible/ansible-runner/blob/master/ansible_runner/utils.py#L337

**Comment by matburt** [comment] 2019-05-24 22:22
I think probably the solution here is for you to either point the artifact directory at a filesystem that supports mkfifo or we'd have to provide an option to not *use* a FIFO when populating keys like this. I'll leave this open for further comment, I'm not sure this is something I particularly want to try to address right now.

**Comment by refactranthony** [comment] 2019-05-24 22:37
How about an option to write the temporary key to a different directory? Or perhaps just pick a different default directory (some temp dir perhaps?). What is the reasoning for writing it to the artifacts directory?

I need the artifacts directory in the network share because I read the playbook output from a different host (seems typical if running in Docker; you want your artifacts folder as a volume).

Is there a convenient way to write artifacts to multiple directories? This seems really awkward on my end, just to work around a temp file location...

**Comment by refactranthony** [comment] 2019-05-28 20:30
Currently working around this issue by subclassing `RunnerConfig` and overriding the `prepare` method. It's a little tricky to do that, as we can no longer use the `interface` `run` and `run_async` functions because they utilize another function, `init_runner`, which has the original `RunnerConfig` coded into it. Another pitfall is the use of `__file__` in the `prepare` method, which will break the callback path when subclassing from my own source directory.

The main change is this, [line 168 of runner_config.py](https://github.com/ansible/ansible-runner/blob/1.3.4/ansible_runner/runner_config.py#L168):

    #self.ssh_key_path = os.path.join(self.artifact_dir, 'ssh_key_data')
    self.ssh_key_path = os.path.join(tempfile.mkdtemp(), 'ssh_key_data')

**Comment by refactranthony** [comment] 2019-05-29 15:47
Oh, awesome. I will do that.

**Comment by AlanCoding** [comment] 2020-09-22 14:56
Closing as duplicate of https://github.com/ansible/ansible-runner/issues/407

**Closed by AlanCoding** 2020-09-22 14:56 UTC
Labels: duplicate
