### ISSUE TITLE
Duplicate output

### ISSUE THREAD

**Issue by Nani-o** [ansible/ansible-runner#182] opened 2019-01-09 16:28 UTC
Using the latest 1.2.0 version, I have some problems trying to use ansible-runner.

I can only reproduce this problem on my Ubuntu server, on my OS X machine this works fine.

python : 3
ansible-runner : 1.2.0
ansible : 2.7.5

Given this simple playbook :
```YAML
---
- hosts: localhost
  gather_facts: no
  tasks:
    - debug:
        msg: ok
    - debug:
        msg: ko
```

I expect to see this (output from ansible-playbook command) : 
```SHELL
$ ansible-playbook toto.yml
 
PLAY [localhost] ***************************************************************************************************************************************

TASK [debug] *******************************************************************************************************************************************
ok: [localhost] => {
    "msg": "ok"
}

TASK [debug] *******************************************************************************************************************************************
ok: [localhost] => {
    "msg": "ko"
}

PLAY RECAP *********************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0

```

Using ansible-runner this is what I get using it as a library : 
```SHELL
$ python3 toto.py

PLAY [localhost] ***************************************************************
ok: [localhost] => {
    "msg": "ok"
}


TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "ok"
}
ok: [localhost] => {
    "msg": "ko"
}


TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "ko"
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```

And using it as a command line : 
```SHELL
$ ansible-runner run . -p toto.yml
 
PLAY [localhost] ***************************************************************

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "ok"
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "ko"
}
localhost                  : ok=2    changed=0    unreachable=0    failed=0



PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0

```

When doing the same from my mac, everything works fine (python3 also on my mac).

**Comment by Nani-o** [comment] 2019-01-10 10:18
I don't fully understand everything in the source code, but I came to the conclusion that removing [thoses lines](https://github.com/ansible/ansible-runner/blob/4a5a1d79104e3b14168b2d6aef1642f07a053ce0/ansible_runner/utils.py#L247-L251) solves my problem.

I am not sure about : 
  1. Why this is not an issue on OS X.
  2. Why this issue is inconsistent on Ubuntu (I just discovered searching for a solution that multiples runs produces extra output, but not the same everytime).

**Comment by matburt** [comment] 2019-01-11 14:56
Rather than just removing the lines, we should look to see what the root cause is and why in certain scenarios we get the right output and duplicate lines otherwise.

I suspect this comes down to what's being flushed out to the stdout file versus the display as we're trying to do event payload + stdout joining.

**Comment by Nani-o** [comment] 2019-01-11 14:58
Hi,

I was pretty sure it was not the fix, I just don't understand what the code trying to accomplish and why this happens. I was just trying to give all the informations I have gathered to help sort this out.

I can help reproduce and test this.

**Comment by chrismeyersfsu** [comment] 2019-02-13 21:47
@Nani-o can you retry to recreate using the master branch of runner? A good bit of fixes have gone in recently.

**Comment by Nani-o** [comment] 2019-02-14 15:21
@chrismeyersfsu The problem seems to be still here.

I installed it using `sudo -H pip3 install git+https://github.com/ansible/ansible-runner@master`. As I said previously, the duplicate output is not always the same, here two consecutive run using the master version : 

```YAML
$ ansible-runner run . -p toto.yml

PLAY [localhost] ***************************************************************
ok: [localhost] => {
    "msg": "ok"
}


TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "ok"
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "ko"
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```

```YAML
$ ansible-runner run . -p toto.yml

PLAY [localhost] ***************************************************************
ok: [localhost] => {
    "msg": "ok"
}


TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "ok"
}
ok: [localhost] => {
    "msg": "ko"
}


TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "ko"
}
localhost                  : ok=2    changed=0    unreachable=0    failed=0



PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```

**Comment by matburt** [comment] 2019-04-24 14:02
Can you see if this is fixed with https://github.com/ansible/ansible-runner/pull/269 ?

**Comment by Nani-o** [comment] 2019-04-24 15:44
Installing with `sudo -H pip3 install git+https://github.com/ryanpetrello/ansible-runner@embedded-event-data --upgrade`, I cannot reproduce 👍 : 
```
ansible-runner run . -p toto.yml

PLAY [localhost] ***************************************************************

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "ok"
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "ko"
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
```

**Comment by ryanpetrello** [comment] 2019-04-24 17:40
@Nani-o I'm condensing my PR into a smaller fix that targets _just_ this issue.

Can you give this a try and confirm it?

`sudo -H pip3 install git+https://github.com/ryanpetrello/ansible-runner@fix-182 --upgrade`

**Comment by Nani-o** [comment] 2019-05-06 07:03
I missed the notification, just tested it, still works fine 👍

**Comment by Nani-o** [comment] 2019-07-30 19:13
@ryanpetrello Just pinging since I have not seen this issue closed.

**Comment by matburt** [comment] 2019-08-09 15:06
I think we'll probably just need to re-base that. There is an outstanding error on the Python 2.7 test run also.

**Comment by darshansiddu01** [comment] 2020-04-28 13:13
@ryanpetrello is there any plan for merging  https://github.com/ansible/ansible-runner/compare/master...ryanpetrello:fix-182 changes to master branch, to make this fix available to everyone?

**Comment by ryanpetrello** [comment] 2020-04-28 13:17
Hey @darshansiddu01,

I lost track of that PR because it didn't _quite_ work (it had side effects), and I never had time to look into it further.  You're welcome to attempt to revive it if you can get it working, though.

**Comment by Nani-o** [comment] 2020-04-28 13:20
Hi, just for the record, I stopped using `ansible-runner` and rely on handlers i've written to use ansible commands via `subprocess`. It's unusable for me if I can't read the logs.

It's sad cause this was the perfect fit for my needs, feel free to close this issue.

**Comment by DjangoCalendar** [comment] 2020-06-17 14:13
Do not close this issue. I am still interested in getting this fixed.  Are there any plans to revisit this topic  ?
@matburt

**Comment by AlanCoding** [comment] 2020-09-22 14:00
Link https://github.com/ansible/ansible-runner/issues/386, when I scroll up here I see duplicated stats, which is the same as that issue.

**Comment by jcmdln** [comment] 2020-10-04 15:18
I recently had issues with duplicate output when I had either `callback_whitelist` or `stdout_callback` set within my `ansible.cfg`. At the time I assumed my experience was caused by using ansible-base 2.10 but having stumbled across this issue and #386 I'm not so sure.

For the time being, a temporary workaround would be to remove either (or both) `callback_whitelist` or `stdout_callback` from `ansible.cfg`.

**Comment by AlanCoding** [comment] 2020-10-05 12:30
I highly suspect this was solved with https://github.com/ansible/ansible-runner/pull/531, if anyone has any new information to contribute a fresh issue would be best.

**Closed by AlanCoding** 2020-10-05 12:30 UTC
Labels: duplicate
