### ISSUE TITLE
ansible_runner.interface.run does not take "settings" keyword argument

### ISSUE THREAD

**Issue by djuran** [ansible/ansible-runner#461] opened 2020-06-10 07:06 UTC
According to the [docs](https://ansible-runner.readthedocs.io/en/latest/source/ansible_runner.html#ansible_runner.interface.run), ansible_runner.interface.run should accept a "settings" argument. This doesn't seem to work in reality though:

`#! /usr/bin/python3

import ansible_runner

ansible_runner.interface.run(playbook='/home/djuran/playbook.yaml',
                             settings={})
`
(env) [djuran@localhost ~]$ env/bin/python3 test.py 
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    settings={})
  File "/home/djuran/env/lib64/python3.6/site-packages/ansible_runner/interface.py", line 177, in run
    r = init_runner(**kwargs)
  File "/home/djuran/env/lib64/python3.6/site-packages/ansible_runner/interface.py", line 64, in init_runner
    rc = RunnerConfig(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'settings'

**Comment by AlanCoding** [comment] 2020-09-21 14:10
Closing as duplicate of https://github.com/ansible/ansible-runner/issues/493

**Closed as completed by AlanCoding** 2020-09-21 14:10 UTC
