### ISSUE TITLE
Quay builds have not run recently

### ISSUE THREAD

**Issue by MallocArray** [ansible/ansible-runner#1081] opened 2022-05-23 18:48 UTC
In the past, when looking at Quay, the ansible-runner images were updated almost daily.  Currently they haven't been updated for 25 days.  Are there no new items to push or is a build process not working as expected?

https://quay.io/repository/ansible/ansible-runner?tab=tags

**Comment by Akasurde** [comment] 2022-05-24 08:48
@MallocArray Thanks for reporting this. We are working on revamping the pypi and container release pipelines. We will keep you posted.

Duplicate of https://github.com/ansible/ansible-runner/issues/1064

**Closed as completed by Akasurde** 2022-05-24 08:48 UTC
