### ISSUE TITLE
Return code/exit status of command line doesn't fit artifacts/<ident>/rc

### ISSUE THREAD

**Issue by Ladas** [ansible/ansible-runner#95] opened 2018-07-17 12:31 UTC
Running ```ansible-runner``` command line seems to be always giving return code 0. Even if there is a failure and I see the value 1 in artifacts/<ident>/rc

**Comment by Ladas** [comment] 2018-07-17 12:32
@matburt doesn't block us, for now I just read the rc from artifacts/<ident>/rc

**Comment by matburt** [comment] 2018-07-18 14:47
This is a dupe of https://github.com/ansible/ansible-runner/issues/48

It's something I'm looking at right now

**Closed by matburt** 2018-07-18 14:47 UTC
