### ISSUE TITLE
Cannot build wheel/image from latest branch

### ISSUE THREAD

**Issue by guliaka** [ansible/ansible-runner#1127] opened 2022-09-12 21:37 UTC
When running make wheel according to documentation get:

```
Fetching changes with git depth set to 20...
Reinitialized existing Git repository in /home/gitlab-runner/builds/xQ3hcFvS/0/ansible/ansible-runner/.git/
Checking out ce8b791b as tst2...
Removing .eggs/
Updating/initializing submodules recursively with git depth set to 20...
Executing "step_script" stage of the job script 00:02
$ make wheel
python3 setup.py bdist_wheel
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help
error: invalid command 'bdist_wheel'
make: *** [Makefile:81: dist/ansible_runner-2.1.5.dev1-py3-none-any.whl] Error 1
```
Python 3.8.12

**Comment by Akasurde** [comment] 2022-09-13 11:34
@guliaka I am not able to reproduce this error. Can you please check if you have the `wheel` package installed or not?

**Comment by Akasurde** [comment] 2022-09-26 13:27
@guliaka Can you please update the required information? Thanks.

**Comment by ssbarnea** [comment] 2022-10-15 07:42
I would close this as user error, installing from source works fine.

While I salute the drop of poetry, I really doubt that `pbr` is the best thing here. On devtools project we went full setuptools-scm, even removed setup.py and fully implemented PEP-517. If anyone wants, we could make a PR to do the same for runner.

**Comment by Akasurde** [comment] 2023-01-17 11:16
Closing this as per https://github.com/ansible/ansible-runner/issues/1127#issuecomment-1279686829. Please feel free to open a new issue, if the problem persists. Thanks.

**Closed as not planned by Akasurde** 2023-01-17 11:16 UTC
Labels: verified, needs_info
