### ISSUE TITLE
Static groups of dynamic groups not getting matched

### ISSUE THREAD

**Issue by onnudilol** [ansible/ansible-runner#1176] opened 2022-12-23 03:19 UTC
## Using static groups of dynamic inventories
I have multiple inventories separated by environment for AWS EC2 instances

```
ansible/
    inventory/
        preprod/
            preprod_aws_ec2.yml
            role_groups.ini
        production/
            production_aws_ec2.yml
            role_groups.ini
        staging/
            staging_aws_ec2.yml
            role_groups.ini
     project/
         deploy.yml
```

I'm using the [Static groups of dynamic groups](https://docs.ansible.com/ansible/latest/inventory_guide/intro_dynamic_inventory.html#id10) feature in Ansible and have groups defined like this in `role_groups.ini`

```
[app_a]

[app_b]

[group_c:children]
app_a
app_b

[app_d]
```

## Using ansible-playbook

I pass hosts as a parameter in `extra-vars`.  Deploying directly using `ansible-playbook` picks up the hosts in the static group correctly

playbook snippet
```
- name: "Deploy to {{ variable_host }}"
  hosts: "{{ variable_host }}"
```

```
ansible-playbook project/deploy.yml -i inventory/staging --extra-vars "variable_host=group_c"

PLAY [Deploy to app_a,app_b] ********************************************************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************************************************************************
ok: [app_a]
ok: [app_b]
```

## Using ansible-runner
Passing the hosts individually using ansible runner works fine.

```
    extra_vars = "app_a,app_b"
    r = ansible_runner.run_async(
        private_data_dir=PRIVATE_DATA_DIR,
        playbook="deploy_docker.yml",
        inventory=f"{PRIVATE_DATA_DIR}/inventory/staging",
        extravars=extra_vars,
    )
```

But the problem is, passing the group doesn't seem to pick up the hosts in the group

```
    extra_vars = "group_c"
    r = ansible_runner.run_async(
        private_data_dir=PRIVATE_DATA_DIR,
        playbook="deploy_docker.yml",
        inventory=f"{PRIVATE_DATA_DIR}/inventory/staging",
        extravars=extra_vars,
    )

Could not match supplied host pattern, ignoring: group_c
PLAY [Deploy to group_c] 
*******************************************
skipping: no hosts matched
```

Moreover, it will still recognise hosts that aren't part of the group and continue tasks for those.

```
    extra_vars = "group_c,app_d"
    r = ansible_runner.run_async(
        private_data_dir=PRIVATE_DATA_DIR,
        playbook="deploy_docker.yml",
        inventory=f"{PRIVATE_DATA_DIR}/inventory/staging",
        extravars=extra_vars,
    )

Could not match supplied host pattern, ignoring: group_c
PLAY [Deploy to group_c,app_d] 
*******************************************

TASK [Gathering Facts] ******************************************************************************************************************************************************************************
ok: [app_d]
```

One workaround I've considered is to just duplicate the static groups I've defined in the `role_groups.ini` file to pass the individual hosts to `extravars`, but it's not a very graceful solution.

Is this a limitation of `ansible-runner`, or am I doing something wrong here?

## Config

```
[defaults]
interpreter_python=/usr/bin/python3
inventory_ignore_extensions=~, .orig, .bak, .cfg, .retry, .pyc, .pyo
display_failed_stderr = yes
```

## Versions

```
ansible-runner --version
2.3.1
```

```
ansible --version
ansible [core 2.12.3]
```

**Comment by Akasurde** [comment] 2023-01-10 14:06
@onnudilol Thanks for reporting this issue. We will verify this and get back to you.

**Comment by Akasurde** [comment] 2023-02-01 16:03
@onnudilol I am not able to reproduce this error. Also, you are using `extravars` as a `str` whereas it requires it to be a `dict`.

Can you please check https://github.com/Akasurde/ansible-reproducers/tree/main/1176 and let me know if replicates your exact environment? Thanks.

**Comment by Akasurde** [comment] 2023-03-17 07:51
@onnudilol Can you please confirm the above comment? Thanks.

**Comment by Akasurde** [comment] 2023-04-11 00:23
I am closing this due to a lack of required information. Please feel free to provide the required information.

**Closed as completed by Akasurde** 2023-04-11 00:23 UTC
Labels: needs_info
