### ISSUE TITLE
Was the image in dockerhub removed?

### ISSUE THREAD

**Issue by xth1** [ansible/ansible-runner#1047] opened 2022-04-22 16:44 UTC
We have a Dockerfile that uses the `ansible/ansible-runner` docker image, but lately, we're getting this error:
```
Step 1/4 : FROM ansible/ansible-runner:1.4.7
pull access denied for ansible/ansible-runner, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

And I see that the image [doesn't seem to be available in Dockerhub anymore](https://registry.hub.docker.com/r/ansible/ansible-runner/). 
Is this expected?

**Comment by ryanmerolle** [comment] 2022-04-23 01:19
Yes.

See #1033

The image on dockerhub was super old and dockerhub was abandoned for quay some time ago.

**Comment by Akasurde** [comment] 2022-04-25 12:00
Duplicate of https://github.com/ansible/ansible-runner/issues/1044

**Closed as completed by Akasurde** 2022-04-25 12:00 UTC
