### ISSUE TITLE
Got KeyError when using ansible.posix.json as callback plugin

### ISSUE THREAD

**Issue by NitroCao** [ansible/ansible-runner#1261] opened 2023-06-26 16:35 UTC
How to reproduce:
* `export ORIGINAL_STDOUT_CALLBACK=ansible.posix.json`
* `ansible-runner run . -p /tmp/demo-playbook.yaml --inventory hosts --omit-event-data --cmdline='-vvv'`
* The content of `/tmp/demo-playbook.yaml` is:
``` yaml
---
- name: Demo task
  hosts: all
  tasks:
    - name: ping
      ping: {}

```
The output is:
```
ansible-playbook [core 2.15.0]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/nitro/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /home/nitro/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-playbook
  python version = 3.11.3 (main, Apr  5 2023, 15:52:25) [GCC 12.2.1 20230201] (/usr/bin/python)
  jinja version = 3.1.2
  libyaml = True
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /home/nitro/Development/vulnk8s/ansible/hosts as it did not pass its verify_file() method
script declined parsing /home/nitro/Development/vulnk8s/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /home/nitro/Development/vulnk8s/ansible/hosts as it did not pass its verify_file() method
Parsed /home/nitro/Development/vulnk8s/ansible/hosts inventory source with ini plugin
[WARNING]: Found both group and host with same name: master
ERROR! Unexpected Exception, this is probably a bug: 'json_indent'
the full traceback was:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ansible/cli/__init__.py", line 659, in cli_executor
    exit_code = cli.run()
                ^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ansible/cli/playbook.py", line 156, in run
    results = pbex.run()
              ^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ansible/executor/playbook_executor.py", line 119, in run
    self._tqm.load_callbacks()
  File "/usr/lib/python3.11/site-packages/ansible/executor/task_queue_manager.py", line 203, in load_callbacks
    self._stdout_callback = callback_loader.get(self._stdout_callback)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ansible/plugins/loader.py", line 855, in get
    return self.get_with_context(name, *args, **kwargs).object
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ansible/plugins/loader.py", line 906, in get_with_context
    obj.__init__(instance, *args, **kwargs)  # pylint: disable=unnecessary-dunder-call
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nitro/.local/lib/python3.11/site-packages/ansible_runner/display_callback/callback/awx_display.py", line 343, in __init__
    super(CallbackModule, self).__init__()
  File "/usr/lib/python3.11/site-packages/ansible_collections/ansible/posix/plugins/callback/json.py", line 76, in __init__
    self._json_indent = self.get_option('json_indent')
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ansible/plugins/callback/__init__.py", line 173, in get_option
    return self._plugin_options[k]
           ~~~~~~~~~~~~~~~~~~~~^^^
KeyError: 'json_indent'
```

Linux distro: Arch Linux.
Ansible version: 2.15.0
Python version: 3.11.3
ansible-runner version: 2.3.3, installed via pip command.

**Comment by NitroCao** [comment] 2023-06-27 08:09
By the way, it works fine when executing ansible-playbook directly. My workaround is to catch the exception and initialize `self._json_indent` to `0` in the exception handler.

**Comment by Igorgro** [comment] 2023-07-22 21:08
Yes, having exactly the same issue when calling ansible-runner from Python code. Running playbook directly or using other callback plugins gives no errors

**Comment by sivel** [comment] 2023-07-24 17:27
Duplicate of https://github.com/ansible/ansible-runner/issues/1077

**Comment by Shrews** [comment] 2023-08-08 15:04
Closing as duplicate.

**Closed as completed by Shrews** 2023-08-08 15:04 UTC

**Comment by gotounix** [comment] 2024-09-29 06:25
@NitroCao I also have the same problem, how did you fix it?
