### ISSUE TITLE
Ansible Vault with ansible-runner for env/envvars not possible

### ISSUE THREAD

**Issue by deadline527** [ansible/ansible-runner#1108] opened 2022-07-25 20:42 UTC
Is it possible to allow for the env/envvars file to be encrypted using ansible-vault?

I know the env/extravars can be successfully decrypted at runtime, but it seems for envvars they get loaded in much earlier. 

Im not sure if this is something anyone has done before, but we really wanted to store secrets as environment variables within the runner environment but currently havent found a way to do this that makes sense.

**Comment by eqrx** [comment] 2022-07-26 13:03
Duplicate of #1099 1099

**Closed as completed by eqrx** 2022-07-26 13:03 UTC
