### ISSUE TITLE
Version of pyOpenSSL is too old

### ISSUE THREAD

**Issue by menardorama** [ansible/ansible-runner#1138] opened 2022-09-29 09:46 UTC
Hi,

We are trying to build a custom ansible runner image for our awx instance.

We need to add a python library to talk to our IPAM (https://gitlab.com/efficientip/solidserverrest)

This python lib use pyopenssl version 22 which breaks compatibility with ansible-runner.

Have you got a solution to manage this or can you bump the pyopenssl version ?

Thanks a lot

**Comment by adamjmont** [comment] 2022-09-30 23:04
Same issue here, custom image built with ansible galaxy community.vmware collection fails for the same reason.

```
Traceback (most recent call last):
  File "/usr/local/bin/ansible-runner", line 5, in <module>
    from ansible_runner.__main__ import main
  File "/usr/local/lib/python3.8/site-packages/ansible_runner/__main__.py", line 48, in <module>
    VERSION = pkg_resources.require("ansible_runner")[0].version
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 800, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pyOpenSSL 22.0.0 (/usr/local/lib/python3.8/site-packages), Requirement.parse('pyOpenSSL<20.0.0'), {'ansible-runner'})
```

**Comment by rafabono** [comment] 2022-10-04 08:51
Hi,
I've the same problem. When I build a new EE image for AWX, and then launch a job with this image, I get this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/ansible-runner", line 5, in <module>
    from ansible_runner.__main__ import main
  File "/usr/local/lib/python3.8/site-packages/ansible_runner/__main__.py", line 48, in <module>
    VERSION = pkg_resources.require("ansible_runner")[0].version
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 800, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pyOpenSSL 22.0.0 (/usr/local/lib/python3.8/site-packages), Requirement.parse('pyOpenSSL<20.0.0'), {'ansible-runner'})
```
My requirements.yml is the next:

```
---
collections:
  - awx.awx
  - community.vmware
  - community.mysql
  - community.postgresql
  - community.general
  - f5networks.f5_modules
  - ansible.posix
  - ansible.windows
  - community.windows
  - lvrfrc87.git_acp  
roles:
  - linux-system-roles.network
```
And my requirements.txt is:

```
urllib3
python-ldap
jmespath
dnspython
PyMySQL
psycopg2-binary
```
The workaround indicates in https://github.com/ansible/awx-ee/issues/137 doesn't work for me. Any solution?

Thanks.

**Comment by kurokobo** [comment] 2022-10-04 22:16
<details>
<summary>
<i>EDIT: Outdated workaround</i>
</summary>
@rafabono
The workaround works for me with your `requirements.yml` and `requirements.txt` on my side (in addition to your file, `bindep.txt` with `python38-devel` and `openldap-devel` seem required for me).

Try appending following `RUN sed` and `RUN cat` (this is just for debugging) lines manually to between the lines `RUN ansible-builder introspect` and `RUN assemble` in your `context/Dockerfile`, then invoke `docker build -t hoge:latest context`.

```dockerfile
...
RUN ansible-builder introspect --sanitize --user-pip=requirements.txt --user-bindep=bindep.txt --write-bindep=/tmp/src/bindep.txt --write-pip=/tmp/src/requirements.txt
RUN sed -i s/vsphere-automation-sdk-python.git/vsphere-automation-sdk-python.git@46aa57de24420ead6af13fe4c8783f1ff66ffcfd/g /tmp/src/requirements.txt     👈👈👈
RUN cat /tmp/src/requirements.txt     👈👈👈
RUN assemble
...
```

During `docker build`, from the build log for `cat` command, you can see the line for `vsphere-automation-sdk-python` in `/tmp/src/requirements.txt` is modified with explicit commit hash `46aa57de24420ead6af13fe4c8783f1ff66ffcfd`.

```txt
...
Step 16/22 : RUN cat /tmp/src/requirements.txt
 ---> Running in fb0d9ffb9ef2
...
git+https://github.com/vmware/vsphere-automation-sdk-python.git@46aa57de24420ead6af13fe4c8783f1ff66ffcfd ; python_version >= '2.7'  # Python 2.6 is not supported  # from collection community.vmware
...
```

To test your image in handy way just `docker run` with your image. If you can get following help message, your image may work with AWX. Ensure imagePullPolicy for EE in AWX is updated to `Always` to pull new image after your build and push.

```bash
$ docker run hoge:latest
The -p option must be specified when not using -m or -r
```
</details>

**Comment by adamjmont** [comment] 2022-10-04 22:44
Workaround works for me when I change "Dockerfile" to "Containerfile". You'll need to do the same if you have podman instead of docker.

Thanks @kurokobo for posting that!

**Comment by rafabono** [comment] 2022-10-05 16:51
Thanks @kurokobo , the workaround works!!!

**Comment by kurokobo** [comment] 2022-10-06 07:38
As @shanemcd did in https://github.com/ansible/awx-ee/pull/141 adding `ansible-runner>=2.2.1` to `requirements.txt` for Ansible Builder is the simplest workaround at this time. Ignore my previous workaround.

The upstream ansible-runner image on quay.io still needs to be updated since the current `latest` image has `ansible-runner-2.1.4.dev2`, so this issue shoud be opened until the image will be updated.

@rafabono @adamjmont 
Just to inform, the workaround has been updated.

**Comment by CWollinger** [comment] 2022-10-06 13:18
@kurokobo thank you for the hint. I can confirm the workaround.

**Comment by michaelkebe** [comment] 2022-10-28 08:57
> The upstream ansible-runner image on quay.io still needs to be updated since the current `latest` image has `ansible-runner-2.1.4.dev2`, so this issue shoud be opened until the image will be updated.

We ran into this issue, too. Please release an updated image on quay.io. The latest release is more than 6 months old.

**Comment by MallocArray** [comment] 2022-10-31 21:12
I would also like an update on when new images will be released. I was hoping to get to ask this at AnsibleFest

**Comment by Akasurde** [comment] 2022-11-01 03:21
We are working on creating a new Ansible Builder which will simplify the build ansible-runner images, please check the progress here https://github.com/users/nitzmahone/projects/1.
This will reduce the dependency on upstream images.

**Comment by MallocArray** [comment] 2022-12-28 21:23
@Akasurde Is this still progressing?  The new Ansible Builder link shows everything in Draft, Ansible 2.14 requires newer python than the last official Ansible provided image, and I have concerns about using a 3rd party's repo for the base image.

Would really be nice if the official ansible-builder image on quay would receive an update to support current versions of Ansible even if there is work being done for a newer version.

**Comment by Akasurde** [comment] 2023-01-17 10:00
@Shrews Can you please provide some updates on the new Ansible Builder version here? Thanks.

**Comment by sivel** [comment] 2023-02-27 16:30
We have decided to no longer maintain, support, or create container images for ansible-runner going forward.

Please see https://github.com/ansible/ansible-runner/issues/1199 for more information.

**Closed as not planned by sivel** 2023-02-27 16:30 UTC

**Comment by ryanmerolle** [comment] 2023-02-27 17:05
@sivel you locked the #1199 thread to conversation so I comment here.

AS an FYI I have provided some [updated runner images](https://github.com/ryanmerolle/ansible-runner/pkgs/container/ansible-runner) for others not savvy with building their own.

Given this expected announcement and the long out of date ansible-runner images available to the community, does the long heralded new version of  ansible-builder have an ETA to a release?

As always, thanks again for all your help!

**Comment by sivel** [comment] 2023-02-27 17:10
@ryanmerolle the target is May. I don't have an exact date at this point.  It will align with the upcoming AAP 2.4 release which is slated for mid June.

Would you like me to link your images in that issue?

**Comment by ryanmerolle** [comment] 2023-02-27 17:21
I do not care if / where you link the images.  I share as needed.

Thanks for the update @sivel
